package telas;


import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/*
import com.sun.jdi.connect.spi.Connection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucas.sbenedito
 */
public class CadastrarOcorrencia extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarDepartamento
     */
    public CadastrarOcorrencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblId = new javax.swing.JLabel();
        iblNome = new javax.swing.JLabel();
        iptId = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        iblTelefone = new javax.swing.JLabel();
        iblId1 = new javax.swing.JLabel();
        iblNome1 = new javax.swing.JLabel();
        iptArea = new javax.swing.JTextField();
        cmbPais = new javax.swing.JComboBox<>();
        cmbPraga = new javax.swing.JComboBox<>();
        iblId2 = new javax.swing.JLabel();
        iblNome2 = new javax.swing.JLabel();
        iblNome3 = new javax.swing.JLabel();
        iptCusto = new javax.swing.JTextField();
        iblNome4 = new javax.swing.JLabel();
        iptAno = new javax.swing.JTextField();
        cmbImpacto = new javax.swing.JComboBox<>();
        cmbMedidas = new javax.swing.JComboBox<>();
        iptNumOcorr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        iblId.setText("ID");
        getContentPane().add(iblId);
        iblId.setBounds(30, 50, 140, 16);

        iblNome.setText("País");
        getContentPane().add(iblNome);
        iblNome.setBounds(30, 110, 140, 16);

        iptId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptIdActionPerformed(evt);
            }
        });
        getContentPane().add(iptId);
        iptId.setBounds(140, 50, 180, 26);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(120, 580, 140, 30);

        iblTelefone.setText("Tipo de Praga");
        getContentPane().add(iblTelefone);
        iblTelefone.setBounds(30, 150, 170, 16);

        iblId1.setText("Area Afetada (Numero KM)");
        getContentPane().add(iblId1);
        iblId1.setBounds(30, 210, 150, 16);

        iblNome1.setText("Numero de Ocorrências");
        getContentPane().add(iblNome1);
        iblNome1.setBounds(30, 260, 140, 16);

        iptArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptAreaActionPerformed(evt);
            }
        });
        getContentPane().add(iptArea);
        iptArea.setBounds(190, 210, 130, 26);

        cmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Honduras", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Puerto Rico", "Uruguay", "Venezuela", "Spain", "France", "Germany", "Italy", "Netherlands", "Portugal", "Sweden", "Switzerland", "Russia", "United Kingdom", "United States" }));
        cmbPais.setToolTipText("");
        cmbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaisActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPais);
        cmbPais.setBounds(140, 100, 180, 26);

        cmbPraga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afídeos", "Lagartas", "Besouros", "Cupins", "Gorgulhos", "Psilídeos", "Tripes", "Cochonilhas", "Nematoides", "Moscas-minadoras" }));
        cmbPraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPragaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPraga);
        cmbPraga.setBounds(140, 150, 180, 26);

        iblId2.setText("Impacto na Produção");
        getContentPane().add(iblId2);
        iblId2.setBounds(30, 310, 150, 16);

        iblNome2.setText("Medidas de Controle");
        getContentPane().add(iblNome2);
        iblNome2.setBounds(30, 370, 140, 16);

        iblNome3.setText("Custo de Controle");
        getContentPane().add(iblNome3);
        iblNome3.setBounds(30, 420, 140, 16);

        iptCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptCustoActionPerformed(evt);
            }
        });
        getContentPane().add(iptCusto);
        iptCusto.setBounds(190, 420, 130, 26);

        iblNome4.setText("Ano");
        getContentPane().add(iblNome4);
        iblNome4.setBounds(30, 480, 140, 16);

        iptAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptAnoActionPerformed(evt);
            }
        });
        getContentPane().add(iptAno);
        iptAno.setBounds(190, 470, 130, 26);

        cmbImpacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixo", "Médio", "Alto", "Critico" }));
        cmbImpacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImpactoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbImpacto);
        cmbImpacto.setBounds(190, 310, 140, 26);

        cmbMedidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Controle biológico", "Controle químico", "Controle cultural", "Controle físico", "Manejo integrado de pragas (MIP)", "Uso de pesticidas seletivos", "Rotação de culturas", "Plantio de variedades resistentes", "Uso de armadilhas", "Aplicação de feromônios" }));
        getContentPane().add(cmbMedidas);
        cmbMedidas.setBounds(190, 360, 140, 26);

        iptNumOcorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptNumOcorrActionPerformed(evt);
            }
        });
        getContentPane().add(iptNumOcorr);
        iptNumOcorr.setBounds(190, 260, 130, 26);

        jLabel6.setText("Cadastrar Ocorrência");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 0, 140, 30);

        setSize(new java.awt.Dimension(423, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iptIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptIdActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String id, pais, tipoPraga, areaAfet, numOcorr, impac, medidas, custo, ano;

        id = iptId.getText();
        pais = cmbPais.getSelectedItem().toString();
        tipoPraga = cmbPraga.getSelectedItem().toString();
        areaAfet = iptArea.getText();
        numOcorr = iptNumOcorr.getText();
        impac = cmbImpacto.getSelectedItem().toString();
        medidas = cmbMedidas.getSelectedItem().toString();
        custo = iptCusto.getText();
        ano = iptAno.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3307/dadosgestao", "root", "p@$$w0rd");

            // ENVIAR DADOS PARA O BANCO DE DADOS
            PreparedStatement st = conectado.prepareStatement("INSERT INTO dados_pragas values(?,?,?,?,?,?,?,?,?)");

            st.setString(1, id);
            st.setString(2, pais);
            st.setString(3, tipoPraga);
            st.setString(4, areaAfet);
            st.setString(5, numOcorr);
            st.setString(6, impac);
            st.setString(7, medidas);
            st.setString(8, custo);
            st.setString(9, ano);
            st.executeUpdate(); // SALVAR NO BANCO DE DADOS

            // AVISAR QUE O USUARIO FOI CADASTRADO COM SUCESSO
            JOptionPane.showMessageDialog(null, "Ocorrência cadastrada com sucesso");

            // LIMPAR OS CAMPOS
            iptId.setText("");
            iptArea.setText("");
            iptNumOcorr.setText("");
            iptArea.setText("");
            iptCusto.setText("");
            iptAno.setText("");
            iptId.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o driver JDBC");
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Ocorrência ja registrada!");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar conectar com o banco de dados" + ex.getMessage());

            }

        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void iptAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptAreaActionPerformed

    private void cmbPragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPragaActionPerformed

    private void iptCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptCustoActionPerformed

    private void iptAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptAnoActionPerformed

    private void cmbImpactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImpactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImpactoActionPerformed

    private void iptNumOcorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptNumOcorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptNumOcorrActionPerformed

    private void cmbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarOcorrencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarOcorrencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbImpacto;
    private javax.swing.JComboBox<String> cmbMedidas;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JComboBox<String> cmbPraga;
    private javax.swing.JLabel iblId;
    private javax.swing.JLabel iblId1;
    private javax.swing.JLabel iblId2;
    private javax.swing.JLabel iblNome;
    private javax.swing.JLabel iblNome1;
    private javax.swing.JLabel iblNome2;
    private javax.swing.JLabel iblNome3;
    private javax.swing.JLabel iblNome4;
    private javax.swing.JLabel iblTelefone;
    private javax.swing.JTextField iptAno;
    private javax.swing.JTextField iptArea;
    private javax.swing.JTextField iptCusto;
    private javax.swing.JTextField iptId;
    private javax.swing.JTextField iptNumOcorr;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
