package telas;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author lucas.sbenedito
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
     public Menu(String cargo) {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuDepartamentos = new javax.swing.JMenu();
        itmCadastrar = new javax.swing.JMenuItem();
        itmResolucao = new javax.swing.JMenuItem();
        itmListarUsuarios = new javax.swing.JMenuItem();
        itmExcluir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Screenshot_8.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-630, -70, 1460, 360);

        mnuDepartamentos.setText("Ocorrências");

        itmCadastrar.setText("Registrar Ocorrência");
        itmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmCadastrar);

        itmResolucao.setText("Registrar Resolução");
        itmResolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmResolucaoActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmResolucao);

        itmListarUsuarios.setText("Listar");
        itmListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarUsuariosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmListarUsuarios);

        itmExcluir.setText("Excluir Ocorrência");
        itmExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmExcluir);

        menuBar.add(mnuDepartamentos);

        jMenuItem1.setText("Dados Doença");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        setSize(new java.awt.Dimension(841, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarActionPerformed
        new CadastrarOcorrencia().setVisible(true);

    }//GEN-LAST:event_itmCadastrarActionPerformed

    private void itmListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarUsuariosActionPerformed
        // TODO add your handling code here:
                new ListarOcorrencias().setVisible(true);

    }//GEN-LAST:event_itmListarUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itmResolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmResolucaoActionPerformed
        String codigo;
        codigo = JOptionPane.showInputDialog("Digite o ID da ocorrência resolvida");
        
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3307/dadosgestao", "root", "p@$$w0rd");
            PreparedStatement st = conectado.prepareStatement("SELECT * FROM dados_pragas WHERE id = ?");
            
            st.setString(1, codigo);
            ResultSet u = st.executeQuery();
            
            if(u.next()){
                    new OcorrenciaResolvida(u).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Ocorrência não encontrada");
            }

                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
                }                  
        
    }//GEN-LAST:event_itmResolucaoActionPerformed

    private void itmExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirActionPerformed
         String id;
        id = JOptionPane.showInputDialog("Digite o ID da ocorrência a excluir");

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3307/dadosgestao", "root", "p@$$w0rd");
            
            PreparedStatement st = conectado.prepareStatement("DELETE FROM dados_pragas WHERE id = ?");
            
            st.setString(1, id);  
            int retorno = st.executeUpdate();
            
               if(retorno == 1)
                                JOptionPane.showMessageDialog(null,"Ocorrência com o ID "  + id + " excluida com sucesso!");

                else   
                                 JOptionPane.showMessageDialog(null,"Ocorrência com o ID "  + id + " não existe");

                   

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro" + ex.getMessage());

        }


    }//GEN-LAST:event_itmExcluirActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCadastrar;
    private javax.swing.JMenuItem itmExcluir;
    private javax.swing.JMenuItem itmListarUsuarios;
    private javax.swing.JMenuItem itmResolucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuDepartamentos;
    // End of variables declaration//GEN-END:variables
}
