package telas;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucas.sbenedito
 */
public class OcorrenciaResolvida extends javax.swing.JFrame {

    /**
     * Creates new form AlterarCurso
     */
    public OcorrenciaResolvida() {
        initComponents();
    }

    public OcorrenciaResolvida(ResultSet u) {
        initComponents();
        try{
        iptId2.setText(u.getString("id"));
        iptArea.setText(u.getString("area_afetada"));
        cmbPais.setSelectedItem(u.getString("pais"));
        cmbPraga.setSelectedItem(u.getString("area_afetada"));
        cmbImpacto.setSelectedItem(u.getString("impacto_producao"));
        cmbMedidas.setSelectedItem(u.getString("medidas_controle"));
        iptNumOcorr.setText(u.getString("numero_ocorrencias"));
        iptCusto.setText(u.getString("custo_controle"));
        iptAno.setText(u.getString("ano"));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } 
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnSalvarAlteracoes = new javax.swing.JButton();
        iblId = new javax.swing.JLabel();
        iblNome = new javax.swing.JLabel();
        iptId2 = new javax.swing.JTextField();
        iblTelefone = new javax.swing.JLabel();
        iblId1 = new javax.swing.JLabel();
        iblNome1 = new javax.swing.JLabel();
        iptArea = new javax.swing.JTextField();
        cmbPais = new javax.swing.JComboBox<>();
        cmbPraga = new javax.swing.JComboBox<>();
        iblId2 = new javax.swing.JLabel();
        iblNome2 = new javax.swing.JLabel();
        iblNome3 = new javax.swing.JLabel();
        iptCusto = new javax.swing.JTextField();
        iblNome4 = new javax.swing.JLabel();
        iptAno = new javax.swing.JTextField();
        cmbImpacto = new javax.swing.JComboBox<>();
        cmbMedidas = new javax.swing.JComboBox<>();
        iptNumOcorr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setText("Resolver Ocorrência");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 10, 140, 30);

        btnSalvarAlteracoes.setText("Resolvido");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarAlteracoes);
        btnSalvarAlteracoes.setBounds(210, 580, 110, 27);

        iblId.setText("ID");
        getContentPane().add(iblId);
        iblId.setBounds(90, 90, 160, 16);

        iblNome.setText("País");
        getContentPane().add(iblNome);
        iblNome.setBounds(90, 150, 160, 16);

        iptId2.setEditable(false);
        iptId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptId2ActionPerformed(evt);
            }
        });
        getContentPane().add(iptId2);
        iptId2.setBounds(200, 90, 200, 26);

        iblTelefone.setText("Tipo de Praga");
        getContentPane().add(iblTelefone);
        iblTelefone.setBounds(90, 190, 190, 16);

        iblId1.setText("Area Afetada (Numero KM)");
        getContentPane().add(iblId1);
        iblId1.setBounds(90, 250, 170, 16);

        iblNome1.setText("Numero de Ocorrências");
        getContentPane().add(iblNome1);
        iblNome1.setBounds(90, 300, 160, 16);

        iptArea.setEditable(false);
        iptArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptAreaActionPerformed(evt);
            }
        });
        getContentPane().add(iptArea);
        iptArea.setBounds(250, 250, 150, 26);

        cmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Costa Rica", "Cuba", "Dominican Republic", "Ecuador", "El Salvador", "Guatemala", "Honduras", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Puerto Rico", "Uruguay", "Venezuela", "Spain", "France", "Germany", "Italy", "Netherlands", "Portugal", "Sweden", "Switzerland", "Russia", "United Kingdom", "United States" }));
        getContentPane().add(cmbPais);
        cmbPais.setBounds(200, 140, 200, 26);

        cmbPraga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afídeos", "Lagartas", "Besouros", "Cupins", "Gorgulhos", "Psilídeos", "Tripes", "Cochonilhas", "Nematoides", "Moscas-minadoras" }));
        cmbPraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPragaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPraga);
        cmbPraga.setBounds(200, 190, 200, 26);

        iblId2.setText("Impacto na Produção");
        getContentPane().add(iblId2);
        iblId2.setBounds(90, 350, 170, 16);

        iblNome2.setText("Medidas de Controle");
        getContentPane().add(iblNome2);
        iblNome2.setBounds(90, 410, 160, 16);

        iblNome3.setText("Custo de Controle");
        getContentPane().add(iblNome3);
        iblNome3.setBounds(90, 460, 160, 16);

        iptCusto.setEditable(false);
        iptCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptCustoActionPerformed(evt);
            }
        });
        getContentPane().add(iptCusto);
        iptCusto.setBounds(250, 460, 150, 26);

        iblNome4.setText("Ano");
        getContentPane().add(iblNome4);
        iblNome4.setBounds(100, 510, 160, 16);

        iptAno.setEditable(false);
        iptAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptAnoActionPerformed(evt);
            }
        });
        getContentPane().add(iptAno);
        iptAno.setBounds(250, 510, 150, 26);

        cmbImpacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixo", "Médio", "Alto", "Critico" }));
        cmbImpacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImpactoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbImpacto);
        cmbImpacto.setBounds(250, 350, 160, 26);

        cmbMedidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Controle biológico", "Controle químico", "Controle cultural", "Controle físico", "Manejo integrado de pragas (MIP)", "Uso de pesticidas seletivos", "Rotação de culturas", "Plantio de variedades resistentes", "Uso de armadilhas", "Aplicação de feromônios" }));
        getContentPane().add(cmbMedidas);
        cmbMedidas.setBounds(250, 400, 160, 26);

        iptNumOcorr.setEditable(false);
        iptNumOcorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptNumOcorrActionPerformed(evt);
            }
        });
        getContentPane().add(iptNumOcorr);
        iptNumOcorr.setBounds(250, 300, 150, 26);

        setSize(new java.awt.Dimension(506, 722));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        String id, pais, tipoPraga, areaAfet, numOcorr, impac, medidas, custo, ano;

        id = iptId2.getText();
        pais = cmbPais.getSelectedItem().toString();
        tipoPraga = cmbPraga.getSelectedItem().toString();
        areaAfet = iptArea.getText();
        numOcorr = iptNumOcorr.getText();
        impac = cmbImpacto.getSelectedItem().toString();
        medidas = cmbMedidas.getSelectedItem().toString();
        custo = iptCusto.getText();
        ano = iptAno.getText();

        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/dadosgestao", "root", "p@$$w0rd");
            
            PreparedStatement st = conectado.prepareStatement("INSERT INTO zonas_ajudadas values(?,?, ?, ?, ?)");
            
            st.setString(1, id);
            st.setString(2, pais);
            st.setString(3, areaAfet);
            st.setString(4, medidas);
            st.setString(5, ano);
            int retorno = st.executeUpdate();
            
               if(retorno == 1)
                                JOptionPane.showMessageDialog(null,"Ocorrência atualizado com sucesso!");

                else   
                                 JOptionPane.showMessageDialog(null,"A ocorrência com o id: "  + id + " não existe");

                   

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro" + ex.getMessage());

        }

    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void iptId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptId2ActionPerformed

    private void iptAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptAreaActionPerformed

    private void cmbPragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPragaActionPerformed

    private void iptCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptCustoActionPerformed

    private void iptAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptAnoActionPerformed

    private void cmbImpactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImpactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImpactoActionPerformed

    private void iptNumOcorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iptNumOcorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iptNumOcorrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OcorrenciaResolvida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OcorrenciaResolvida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OcorrenciaResolvida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OcorrenciaResolvida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OcorrenciaResolvida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JComboBox<String> cmbImpacto;
    private javax.swing.JComboBox<String> cmbMedidas;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JComboBox<String> cmbPraga;
    private javax.swing.JLabel iblId;
    private javax.swing.JLabel iblId1;
    private javax.swing.JLabel iblId2;
    private javax.swing.JLabel iblNome;
    private javax.swing.JLabel iblNome1;
    private javax.swing.JLabel iblNome2;
    private javax.swing.JLabel iblNome3;
    private javax.swing.JLabel iblNome4;
    private javax.swing.JLabel iblTelefone;
    private javax.swing.JTextField iptAno;
    private javax.swing.JTextField iptArea;
    private javax.swing.JTextField iptCusto;
    private javax.swing.JTextField iptId2;
    private javax.swing.JTextField iptNumOcorr;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
